services:
  - type: web
    name: cartodatasup-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn backend.wsgi:application
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: cartodatasup-db
          property: connectionString
