# Generated by Django 5.1.6 on 2025-03-06 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('detailed_category', models.CharField(max_length=255)),
                ('is_selective', models.BooleanField(default=False)),
                ('gps_coordinates', models.CharField(blank=True, max_length=50, null=True)),
                ('capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uai_code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('department_code', models.CharField(max_length=5)),
                ('department_name', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('academy', models.CharField(max_length=100)),
                ('commune', models.CharField(max_length=100)),
                ('is_public', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Candidature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_year', models.IntegerField()),
                ('total_candidates', models.IntegerField()),
                ('female_candidates', models.IntegerField()),
                ('boursier_candidates', models.IntegerField()),
                ('neo_bac_general', models.IntegerField()),
                ('neo_bac_techno', models.IntegerField()),
                ('neo_bac_pro', models.IntegerField()),
                ('admitted_total', models.IntegerField()),
                ('admitted_females', models.IntegerField()),
                ('admitted_boursiers', models.IntegerField()),
                ('admitted_neo_bac_general', models.IntegerField()),
                ('admitted_neo_bac_techno', models.IntegerField()),
                ('admitted_neo_bac_pro', models.IntegerField()),
                ('mention_tb', models.IntegerField(default=0)),
                ('mention_b', models.IntegerField(default=0)),
                ('mention_ab', models.IntegerField(default=0)),
                ('mention_none', models.IntegerField(default=0)),
                ('same_academy_admissions', models.IntegerField(default=0)),
                ('different_academy_admissions', models.IntegerField(default=0)),
                ('admitted_before_bac', models.IntegerField(default=0)),
                ('admitted_after_procedure_start', models.IntegerField(default=0)),
                ('admitted_after_procedure_end', models.IntegerField(default=0)),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidatures', to='admissions.formation')),
            ],
        ),
        migrations.AddField(
            model_name='formation',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formations', to='admissions.institution'),
        ),
    ]
