# Generated by Django 5.1.6 on 2025-04-07 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='is_public',
            field=models.CharField(max_length=100),
        ),
    ]
