# Generated by Django 5.1.6 on 2025-04-07 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0002_alter_institution_is_public'),
    ]

    operations = [
        migrations.RenameField(
            model_name='institution',
            old_name='is_public',
            new_name='status',
        ),
    ]
