# Generated by Django 5.1.6 on 2025-04-16 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0003_rename_is_public_institution_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidature',
            name='admitted_neo_bac',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidature',
            name='admitted_others_candidates',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
