# Generated by Django 5.1.6 on 2026-06-21 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0004_candidature_admitted_neo_bac_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formation',
            name='category',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='formation',
            name='detailed_category',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='formation',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='institution',
            name='name',
            field=models.TextField(),
        ),
    ]
